# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 08:24
from __future__ import unicode_literals

from django.db import migrations
from employees.models import Employee, Departament


def populate_departaments(apps, schema_editor):
    d = Departament(name='Отдел 1')
    d.save()
    d = Departament(name='Отдел 2')
    d.save()
    d = Departament(name='Отдел 3')
    d.save()


def populate_employees(apps, schema_editor):
    d1 = Departament.objects.get(name__iexact='Отдел 1')
    d2 = Departament.objects.get(name__iexact='Отдел 2')
    d3 = Departament.objects.get(name__iexact='Отдел 3')
    e = Employee(name='Иван', surname='Арбузов', middle_name='Иванович', birthday='1990-01-01', email='a@a.a',
                 phone='+79999999999', begin_work='2010-01-01', post='разработчик', departament=d1)
    e.save()
    e = Employee(name='Иван', surname='Антонов', middle_name='Иванович', birthday='1990-01-01', email='a@a.a',
                 phone='+79999999999', begin_work='2010-01-01', post='разработчик', departament=d1)
    e.save()
    e = Employee(name='Иван', surname='Богданов', middle_name='Иванович', birthday='1990-01-02', email='b@a.a',
                 phone='+79999999998', begin_work='2010-01-01', post='разработчик', departament=d2)
    e.save()
    e = Employee(name='Иван', surname='Боряев', middle_name='Иванович', birthday='1990-01-02', email='b@a.a',
                 phone='+79999999998', begin_work='2010-01-01', post='разработчик', departament=d2)
    e.save()
    e = Employee(name='Иван', surname='Ванков', middle_name='Иванович', birthday='1990-01-03', email='c@a.a',
                 phone='+79999999997', begin_work='2010-02-01', post='разработчик', departament=d3)
    e.save()
    e = Employee(name='Иван', surname='Волков', middle_name='Иванович', birthday='1990-01-03', email='c@a.a',
                 phone='+79999999997', begin_work='2010-02-01', post='разработчик', departament=d3)
    e.save()
    e = Employee(name='Иван', surname='Викторов', middle_name='Иванович', birthday='1990-01-03', email='c@a.a',
                 phone='+79999999997', begin_work='2010-02-01', post='разработчик', departament=d3)
    e.save()
    e = Employee(name='Иван', surname='Городецкий', middle_name='Иванович', birthday='1990-01-04', email='d@a.a',
                 phone='+79999999996', begin_work='2010-02-01', post='разработчик', departament=d1)
    e.save()
    e = Employee(name='Иван', surname='Домов', middle_name='Иванович', birthday='1990-01-05', email='e@a.a',
                 phone='+79999999995', begin_work='2010-03-01', post='разработчик', departament=d2)
    e.save()
    e = Employee(name='Иван', surname='Дарьев', middle_name='Иванович', birthday='1990-01-05', email='e@a.a',
                 phone='+79999999995', begin_work='2010-03-01', post='разработчик', departament=d2)
    e.save()
    e = Employee(name='Иван', surname='Дивеев', middle_name='Иванович', birthday='1990-01-05', email='e@a.a',
                 phone='+79999999995', begin_work='2010-03-01', post='разработчик', departament=d2)
    e.save()
    e = Employee(name='Иван', surname='Дамков', middle_name='Иванович', birthday='1990-01-05', email='e@a.a',
                 phone='+79999999995', begin_work='2010-03-01', post='разработчик', departament=d2)
    e.save()
    e = Employee(name='Иван', surname='Евалов', middle_name='Иванович', birthday='1990-01-06', email='f@a.a',
                 phone='+79999999994', begin_work='2010-03-01', post='разработчик', departament=d3)
    e.save()
    e = Employee(name='Иван', surname='Жиров', middle_name='Иванович', birthday='1990-01-07', email='ag@a.a',
                 phone='+79999999993', begin_work='2010-04-01', post='разработчик', departament=d1)
    e.save()
    e = Employee(name='Иван', surname='Замков', middle_name='Иванович', birthday='1990-01-08', email='h@a.a',
                 phone='+79999999992', begin_work='2010-04-01', post='разработчик', departament=d2)
    e.save()
    e = Employee(name='Иван', surname='Иванов', middle_name='Иванович', birthday='1990-01-09', email='i@a.a',
                 phone='+79999999991', begin_work='2010-05-01', end_work='2014-01-01', post='разработчик',
                 departament=d3)
    e.save()
    e = Employee(name='Иван', surname='Копченов', middle_name='Иванович', birthday='1990-01-10', email='g@a.a',
                 phone='+79999999990', begin_work='2010-05-01', end_work='2014-01-01', post='разработчик',
                 departament=d1)
    e.save()
    e = Employee(name='Иван', surname='Лунков', middle_name='Иванович', birthday='1990-01-11', email='k@a.a',
                 phone='+79999999989', begin_work='2010-06-01', end_work='2014-01-02', post='разработчик',
                 departament=d2)
    e.save()
    e = Employee(name='Иван', surname='Марков', middle_name='Иванович', birthday='1990-01-12', email='l@a.a',
                 phone='+79999999979', begin_work='2010-06-01', end_work='2014-01-02', post='разработчик',
                 departament=d3)
    e.save()
    e = Employee(name='Иван', surname='Норов', middle_name='Иванович', birthday='1990-01-13', email='m@a.a',
                 phone='+79999999969', begin_work='2010-07-01', end_work='2014-01-03', post='разработчик',
                 departament=d1)
    e.save()
    e = Employee(name='Иван', surname='Орлов', middle_name='Иванович', birthday='1990-01-14', email='n@a.a',
                 phone='+79999999959', begin_work='2010-07-01', end_work='2014-01-03', post='разработчик',
                 departament=d2)
    e.save()
    e = Employee(name='Иван', surname='Петров', middle_name='Иванович', birthday='1990-01-15', email='o@a.a',
                 phone='+79999999949', begin_work='2010-08-01', end_work='2014-01-04', post='разработчик',
                 departament=d3)
    e.save()
    e = Employee(name='Иван', surname='Ростов', middle_name='Иванович', birthday='1990-01-16', email='p@a.a',
                 phone='+79999999939', begin_work='2010-08-01', end_work='2014-01-04', post='разработчик',
                 departament=d1)
    e.save()


class Migration(migrations.Migration):
    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_departaments),
        migrations.RunPython(populate_employees),
    ]
